language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - SYMFONY_VERSION="4.2.*"
  - SYMFONY_VERSION="4.4.*"
  - SYMFONY_VERSION="5.0.*"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - rm -rf composer.lock vendor/
  - composer require "symfony/symfony/console:${SYMFONY_VERSION}" --no-update
  - composer require "symfony/symfony/filesystem:${SYMFONY_VERSION}" --no-update
  - composer require "symfony/symfony/framework-bundle:${SYMFONY_VERSION}" --no-update
  - composer require "symfony/symfony/process:${SYMFONY_VERSION}" --no-update
  - composer require "symfony/symfony/serializer:${SYMFONY_VERSION}" --no-update
  - composer require "symfony/symfony/validator:${SYMFONY_VERSION}" --no-update

install: COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit

notifications:
  email: eugone.yann@gmail.com
